mysite/mysite/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'mysite.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^stock/', include('stock.urls', namespace="stock")),
    url(r'^admin/', include(admin.site.urls)),
)

mysite/stock/urls.py
from django.conf.urls import patterns, url
from stock import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    url(r'^(?P<category_id>\d+)/add$', views.detail, name='detail'),
    url(r'^(?P<category_id>\d+)/remove$', views.remove, name='remove'),
    url(r'^(?P<category_id>\d+)/$', views.contents, name='contents'),
    url(r'^(?P<category_id>\d+)/addItem/$', views.addItem, name='addItem'),
    url(r'^(?P<category_id>\d+)/removeItem/$', views.removeItem, name='removeItem'),
)

mysite/stock/models.py
from django.db import models

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=50)

    def __unicode__(self):
        return self.name

class Item(models.Model):
    category = models.ForeignKey(Category)
    name = models.CharField(max_length=50, primary_key=True)
    quantity = models.IntegerField(default=0)

    def __unicode__(self):
        return self.name

mysite/stock/views.py
from django.core.urlresolvers import reverse
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404

from stock.models import Category, Item
# Create your views here.
def index(request):
    category_list = Category.objects.all()
    context = {'category_list': category_list}
    return render(request, 'categories/index.html', context)

def detail(request, category_id):
    category = get_object_or_404(Category, pk=category_id)
    return render(request, 'categories/detail.html', {'category': category})

def contents(request, category_id):
    category = get_object_or_404(Category, pk=category_id)
    return render(request, 'categories/contents.html', {'category': category})

def addItem(request, category_id):
    c = get_object_or_404(Category, pk=category_id)
    
    obj, created = Item.objects.get_or_create(name=request.POST['item'], category_id=category_id)

    obj.quantity += int(request.POST['numberOfItems'])
    obj.save()
    return HttpResponseRedirect(reverse('stock:contents', args=(c.id,)))

def remove(request, category_id):
    category = get_object_or_404(Category, pk=category_id)
    return render(request, 'categories/remove.html', {'category': category})

def removeItem(request, category_id):
    c = get_object_or_404(Category, pk=category_id)
    
    obj = Item.objects.get(name=request.POST['item'], category_id=category_id)

    obj.quantity -= int(request.POST['numberOfItems'])
    obj.save()
    return HttpResponseRedirect(reverse('stock:contents', args=(c.id,)))    

mysite/stock/templates/categories/contents.html
{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'categories/style.css' %}" />

<h3>{{ category.name }}</h3>

<br>

<ul>
{% for item in category.item_set.all %}
    <li>{{ item.name }} -- {{ item.quantity }} </li>
{% endfor %}
</ul>

<br>

<div id="contentsLinks">
    <a href="{% url 'stock:remove' category.id %}">Remove from stock</a><br>
    <a href="{% url 'stock:detail' category.id %}">Add to stock</a><br>
    <a href="{% url 'stock:index' %}">Back to home page</a>
</div>

mysite/stock/templates/categories/detail.html
{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'categories/style.css' %}" />

<h3>{{ category.name }}</h3>

<br>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<div id="addItems">
    <form action="{% url 'stock:addItem' category.id %}" method="post">
    {% csrf_token %}
    Item name: <input type="text" name="item"><br>
    Quantity: <input type="text" name="numberOfItems"><br>
    <input type="submit" value="Add Item" />
    </form>
</div>

mysite/stock/templates/categories/index.html
{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'categories/style.css' %}" />

<div id="mainTitle">
    <h3>
        Welcome to your stock page, please choose a category
    </h3>
</div>

<br>

{% if category_list %}
    <ul>
    {% for category in category_list %}
        <li><a href="/stock/{{ category.id }}">{{ category.name }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No categories are available.</p>
{% endif %}

mysite/stock/templates/categories/remove.html
{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'categories/style.css' %}" />

<h3>{{ category.name }}</h3>

<br>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<div id="removeItems">
    <form action="{% url 'stock:removeItem' category.id %}" method="post">
    {% csrf_token %}
    Item name: <input type="text" name="item"><br>
    Quantity: <input type="text" name="numberOfItems"><br>
    <input type="submit" value="Remove Item" />
    </form>
</div>